// package com.kashan.twitter_clone.entity.UserRelation.CompositeKey;

// import java.io.Serializable;

// import lombok.AllArgsConstructor;
// import lombok.Getter;
// import lombok.NoArgsConstructor;

// @NoArgsConstructor
// @AllArgsConstructor
// @Getter
// public class BlockID implements Serializable {
//     private Long blocker;
//     private Long blocked;

//     // Generated by IDE
//     @Override
//     public int hashCode() {
//         final int prime = 31;
//         int result = 1;
//         result = prime * result + ((blocker == null) ? 0 : blocker.hashCode());
//         result = prime * result + ((blocked == null) ? 0 : blocked.hashCode());
//         return result;
//     }

//     @Override
//     public boolean equals(Object obj) {
//         if (this == obj)
//             return true;
//         if (obj == null)
//             return false;
//         if (getClass() != obj.getClass())
//             return false;
//         BlockID other = (BlockID) obj;
//         if (blocker == null) {
//             if (other.blocker != null)
//                 return false;
//         } else if (!blocker.equals(other.blocker))
//             return false;
//         if (blocked == null) {
//             if (other.blocked != null)
//                 return false;
//         } else if (!blocked.equals(other.blocked))
//             return false;
//         return true;
//     }
// }
